import type { NextPage } from "next";
import Head from "next/head";
import { Track } from "@uniformdev/context-react";
import { IPage, ITalk } from "../@types/generated/contentful";
import Navbar from "./Navbar";
import Footer from "./Footer";
import { PageComponentsList } from "./PageComponentsList";
import { ENRICHMENT_TAG_FIELD_ID } from "../lib/constants";
import TalksContext from "../lib/talksContext";

export type PageProps = {
  preview: boolean;
  page: IPage;
  talks: ITalk[] | undefined;
};

const Page: NextPage<PageProps> = ({ page, talks }) => {
  const behaviour = [];
  //@todo fork "contentful-typescript-codegen" package to support Context fields formats
  if (page?.fields && page.fields[ENRICHMENT_TAG_FIELD_ID]) {
    // @ts-expect-error
    behaviour.push(...page.fields[ENRICHMENT_TAG_FIELD_ID]);
  }
  const { components } = page?.fields || {};
  return (
    <Track behavior={behaviour}>
      <Navbar />
      <Head>
        <title>Uniform Context + Contentful + NextJS</title>
        <meta
          name="description"
          content="Generated by create next app, modified with typescript, etc"
        />
      </Head>
      <TalksContext.Provider value={talks}>
        {components && <PageComponentsList components={components} />}
      </TalksContext.Provider>
      <Footer />
    </Track>
  );
};

export default Page;
